name: auto-merge

on:
  pull_request_target:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.6
        with:
          target: minor
          github-token: ${{ secrets.GH_TOKEN }}
